# filename: .github/workflows/bld_cmd_ci.yml
name: Build with CMD and CI on VS
# Explainer on the ${{ }} syntax:
# https://docs.github.com/en/actions/writing-workflows
#  /choosing-what-your-workflow-does
#  /accessing-contextual-information-about-workflow-runs
# The ">-" continuation here allows the name to span multiple lines
run-name: >-
  ci-cmd-${{ github.event.inputs.build
    }}-vs${{ github.event.inputs.vs_year
    }}-${{ github.event.inputs.architecture
    }}-${{ github.event.inputs.target
    }}-Py_${{ github.event.inputs.python_version
    }}-h_${{ github.event.inputs.hack }}

# Workflow dispatch allows manual triggering of the workflow with inputs    
on:
  workflow_dispatch:
    inputs:
      # Random conditional to hang various features off of
      hack:
        description: "Enable HACK mode"
        required: false
        default: "false"
      # What to build, default to EmulatorPkg for speed
      build:
        description: "Pkg ( ie. EmulatorPkg, OvmfPkg, Edk2, All )"
        required: false
        default: "EmulatorPkg"
      # Visual Studio year, default to 22 for latest (2022)
      vs_year:
        description: "Visual Studio Year ( 22 | 19 )"
        required: false
        default: "22"
      # Build target, default to DEBUG for faster builds
      target:
        description: "Build target (DEBUG | RELEASE)"
        required: false
        default: "DEBUG"
      # Architecture to build for, default to X64
      architecture:
        description: "Build architecture (X64 | IA32 )"
        required: false
        default: "X64"
      # Python version to use, ensure the version is downloadable
      python_version:
        description: "Python version to use"
        required: false
        default: "3.12.9"

jobs:
  build:
    # Use the Windows Server 2022 or 2019 runner
    runs-on: windows-20${{ github.event.inputs.vs_year }}
    # Make a global environment block for the workflow
    env:
      GH_WORKSPACE: ${{ github.workspace }}
      GH_HEAD_SHA: ${{ github.sha }}
      IASL_PREFIX: C:\ProgramData\chocolatey\bin\
      CLANG_BIN: C:\Program Files\LLVM\bin\
      NASM_PREFIX: C:\Program Files\NASM\
      PYTHON_COMMAND: D:\Python${{ github.event.inputs.python_version }}\python.exe
      PYTHON_PATH: D:\Python${{ github.event.inputs.python_version }}
      PYTHON_VERSION: ${{ github.event.inputs.python_version }}
      PYTHON_SETUP: python-${{ github.event.inputs.python_version }}-amd64.exe
      STUART: D:\Python${{ github.event.inputs.python_version }}\Scripts\stuart
      GH_REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      GH_WORKFLOW_NAME: ${{ github.workflow }}
      BUILD_BAT: mk_bat.py
      REPO_PATH: D:\r
      EDK2_PATH: D:\r\Edk2
      ARTIFACT_PATH: D:\artifact
      EMU_HOST: WinHost
      CHAIN: VS20${{ github.event.inputs.vs_year }}
      ARCH: ${{ github.event.inputs.architecture }}
      TRGT: ${{ github.event.inputs.target }}

    defaults:
      run:
        shell: cmd
    steps:
      - name: List Environment Variables
        run: set

      - name: Clone Repo
        run: git clone --recurse-submodules --depth 1 --shallow-submodules %GH_REPO_URL% %REPO_PATH%

      # - name: Checkout Repository recursively with long-files
      #   uses: actions/checkout@v4
      #   with:
      #     submodules: recursive     # Initialize and update submodules
      #     long-paths: true          # Enable long path support

      - name: Install Py${{ github.event.inputs.python_version }} and NASM and IASL
        run: |
          curl -o ${{ github.workspace }}\%PYTHON_SETUP% https://www.python.org/ftp/python/%PYTHON_VERSION%/%PYTHON_SETUP%
          ${{ github.workspace }}\%PYTHON_SETUP% /quiet TargetDir=%PYTHON_PATH%
          choco install nasm iasl -y

      - name: Install Pip Requirements
        run: |
          %PYTHON_COMMAND% -m pip install --upgrade pip
          %PYTHON_COMMAND% -m pip install -r "%EDK2_PATH%\pip-requirements.txt"

      - name: Build BaseTools
        run: |
          pushd "%EDK2_PATH%"
          call edksetup.bat Reconfig %CHAIN%
          %PYTHON_COMMAND% BaseTools\Edk2ToolsBuild.py -t %CHAIN%

      - name: Build Edk2
        # Compiler #2065: EmbeddedPkg\...\VirtualRealTimeClockLib.c(89): 'BUILD_EPOCH': undeclared
        continue-on-error: true
        if: >-
          ${{ github.event.inputs.build == 'All' ||
              github.event.inputs.build == 'Edk2' }}
        run: |
          pushd "%EDK2_PATH%"
          call edksetup.bat Reconfig %CHAIN%
          %STUART%_setup -c .pytool\CISettings.py -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%
          %STUART%_update -c .pytool\CISettings.py -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%
          %STUART%_ci_build -c .pytool\CISettings.py -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%

      - name: Build EmulatorPkg
        if: >-
          ${{ github.event.inputs.build == 'All' ||
              github.event.inputs.build == 'EmulatorPkg' ||
              github.event.inputs.hack == 'true' }}
        run: |
          pushd "%EDK2_PATH%"
          call edksetup.bat Reconfig %CHAIN%
          %STUART%_setup -c EmulatorPkg\PlatformCI\PlatformBuild.py -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%
          %STUART%_update -c EmulatorPkg\PlatformCI\PlatformBuild.py -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%
          %STUART%_build -c EmulatorPkg\PlatformCI\PlatformBuild.py -a %ARCH% TOOL_CHAIN_TAG=%CHAIN% TARGET=%TRGT%

      - name: Build OvmfPkg
        if: >-
          ${{ github.event.inputs.build == 'All' ||
              github.event.inputs.build == 'OvmfPkg' ||
              github.event.inputs.hack == 'true' }}

        run: |
          pushd "%EDK2_PATH%"
          call edksetup.bat Reconfig %CHAIN%
          %STUART%_setup -c OvmfPkg\PlatformCI\PlatformBuild.py -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%
          %STUART%_update -c OvmfPkg\PlatformCI\PlatformBuild.py -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%
          %STUART%_build -c OvmfPkg\PlatformCI\PlatformBuild.py -a %ARCH% TOOL_CHAIN_TAG=%CHAIN% TARGET=%TRGT%

      - name: Build Single Pkg ${{ github.event.inputs.build }}
        if: >-
          ${{ github.event.inputs.build != 'All' &&
              github.event.inputs.build != 'OvmfPkg' &&
              github.event.inputs.build != 'EmulatorPkg' }}
        run: |
          pushd "%EDK2_PATH%"
          %STUART%_setup -c .pytool\CISettings.py -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%
          %STUART%_update -c .pytool\CISettings.py -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%
          %STUART%_ci_build -c .pytool\CISettings.py -p ${{ github.event.inputs.build }} -a %ARCH% -t %TRGT% TOOL_CHAIN_TAG=%CHAIN%

      - name: Gather VS Environment Data
        run: |
          set VOLUME=%ARTIFACT_PATH%\Emulator%ARCH%\%TRGT%_%CHAIN%\%ARCH%\Host
          pushd "%EDK2_PATH%"
          call edksetup.bat Reconfig %CHAIN%
          mkdir %VOLUME%\EFI\Boot
          mkdir %VOLUME%\EFI\Tools
          pushd %ARTIFACT_PATH%
          set > vmInfoEnvVars.txt
          vswhere -format json > vmInfoVswhere.json
          jq -r ".[0].properties.setupEngineFilePath" vmInfoVswhere.json > vmInfoVsSetupTool.txt
          for /f "delims=;" %%p in (vmInfoVsSetupTool.txt) do (
            set VS_SETUP_PATH=%%~dpp
          )
          jq -r ".[0].installationPath" vmInfoVswhere.json > vmInfoVsInstallPath.txt
          for /f "delims=;" %%p in (vmInfoVsInstallPath.txt) do (
            echo.| "%VS_SETUP_PATH%\vs_installer.exe" export --quiet --installPath "%%p" --config vmInfoVsConfig.json
          )

      - name: Package Build Outputs
        # Robocopy will likely throw an error on one of these, so ignore and continue
        # continue-on-error: true
        run: |
          set VOLUME=%ARTIFACT_PATH%\Emulator%ARCH%\%TRGT%_%CHAIN%\%ARCH%\Host
          pushd "%EDK2_PATH%\Build"
          echo "%CD%"
          xcopy %REPO_PATH%\.github\workflows\*.yml "%ARTIFACT_PATH%\"
          for /d %%p in (. *) do (
            if exist %EDK2_PATH%\Build\%%p\vmInfo* (
              xcopy %EDK2_PATH%\Build\%%p\vmInfo* "%ARTIFACT_PATH%\%%p\" /D /Y
            )
            if exist %EDK2_PATH%\Build\%%p\BUILDLOG*.txt (
              xcopy %EDK2_PATH%\Build\%%p\BUILDLOG*.txt "%ARTIFACT_PATH%\%%p\" /D /Y
            )
            if exist %EDK2_PATH%\Build\%%p\*LOG.txt (
              xcopy %EDK2_PATH%\Build\%%p\*LOG.txt "%ARTIFACT_PATH%\%%p\" /D /Y
            )
            if exist %EDK2_PATH%\Build\%%p\All\%TRGT%_%CHAIN%\%ARCH%\*.efi (
              xcopy %EDK2_PATH%\Build\%%p\All\%TRGT%_%CHAIN%\%ARCH%\*.efi "%ARTIFACT_PATH%\%%p\%TRGT%_%CHAIN%\%ARCH%\" /D /Y
            )
            if exist %EDK2_PATH%\Build\%%p\%TRGT%_%CHAIN%\%ARCH%\*.efi (
              xcopy %EDK2_PATH%\Build\%%p\%TRGT%_%CHAIN%\%ARCH%\*.efi "%ARTIFACT_PATH%\%%p\%TRGT%_%CHAIN%\%ARCH%\" /D /Y
            )
            if exist %EDK2_PATH%\Build\%%p\%TRGT%_%CHAIN%\%ARCH%\%EMU_HOST%* (
              xcopy %EDK2_PATH%\Build\%%p\%TRGT%_%CHAIN%\%ARCH%\%EMU_HOST%* "%VOLUME%\" /D /Y
            )
            if exist %EDK2_PATH%\Build\%%p\%TRGT%_%CHAIN%\FV\* (
              xcopy %EDK2_PATH%\Build\%%p\%TRGT%_%CHAIN%\FV\* "%ARTIFACT_PATH%\%%p\%TRGT%_%CHAIN%\FV\" /D /Y
            )
          )

      - name: Build UEFI Volume
        run: |
          set VOLUME=%ARTIFACT_PATH%\Emulator%ARCH%\%TRGT%_%CHAIN%\%ARCH%\Host
          pushd %ARTIFACT_PATH%
          echo %GH_HEAD_SHA% > vmInfo%CHAIN%-%ARCH%-%TRGT%-Py%PYTHON_VERSION%.txt
          dir /s /b /a:-d > repoFileListing.txt
          dir /s /b /a:d > repoDirListing.txt
          findstr /m /c:"%GH_WORKFLOW_NAME%" %REPO_PATH%\.github\workflows\*.yml > repoWorkflowFile.txt
          for /f "delims=;" %%p in (repoWorkflowFile.txt) do (
            set GH_WORKFLOW_FILE=%%~pnxp
          )
          for %%p in (%VOLUME%) do (
            echo efiVolume: %%~pnxp>> README.txt
          )
          set BAT_FILE=build%CHAIN%-%ARCH%-%TRGT%-Py%PYTHON_VERSION%.bat
          %PYTHON_COMMAND% %REPO_PATH%\%BUILD_BAT% D:%GH_WORKFLOW_FILE% D:%BAT_FILE%
          echo gitTag: %GH_HEAD_SHA%>> README.txt
          echo workflowFile: %GH_WORKFLOW_FILE%>> README.txt
          echo batFile: %BAT_FILE%>> README.txt
          for /d %%p in (*) do (
            if exist %ARTIFACT_PATH%\%%p\%TRGT%_%CHAIN%\%ARCH%\*.efi (
              xcopy %ARTIFACT_PATH%\%%p\%TRGT%_%CHAIN%\%ARCH%\*.efi %VOLUME%\EFI\Tools\  /D /Y
            )
          )
          if exist %VOLUME%\EFI\Tools\Shell.efi (
            copy %VOLUME%\EFI\Tools\Shell.efi %VOLUME%\EFI\Boot\bootx64.efi
          )

      - name: Make VHDX File in pwsh for win2019
        shell: pwsh
        if: ${{ github.event.inputs.vs_year == '19' }}
        run: |
          $OVM_OUT = "${env:ARTIFACT_PATH}\Ovmf${env:ARCH}\${env:TRGT}_${env:CHAIN}"
          if (Test-Path -path $OVM_OUT) {
            $EMU_OUT = "${env:ARTIFACT_PATH}\Emulator${env:ARCH}\${env:TRGT}_${env:CHAIN}\${env:ARCH}\Host"
            $VhdPath = "${OVM_OUT}\efi_disk.vhdx"
            $DirectorySizeBytes = (Get-ChildItem -Path "${EMU_OUT}\EFI" -Recurse | Measure-Object -Property Length -Sum).Sum
            $VhdSizeBytes = [math]::Ceiling($DirectorySizeBytes * 2 / 1048576 ) * 1048576
            $VhdSizeBytes = [math]::Max($VhdSizeBytes, 50 * 1048576)
            $VhdSizeMB = $VhdSizeBytes / 1048576
            $DrvLetter = 'V'
            $DiskPartScript = @("",
              "create vdisk file=$VhdPath maximum=$VhdSizeMB type=expandable",
              "select vdisk file=$VhdPath",
              "attach vdisk",
              "create partition primary",
              "format fs=fat quick",
              "assign letter=$DrvLetter",
              "exit",
            "") -join "`n"
            $DiskPartScript | diskpart
            Copy-Item -Path ${EMU_OUT}\EFI -Destination "${DrvLetter}:\" -Recurse -Force
            $DiskPartScript = ("",
              "select vdisk file=$VhdPath",
              "select volume=$DrvLetter",
              "remove letter=$DrvLetter",
              "detach vdisk",
              "exit",
            "") -join "`n"
            $DiskPartScript | diskpart
            $base = New-Object System.Uri("${env:ARTIFACT_PATH}\")
            $fullpath = New-Object System.Uri("${OVM_OUT}")
            $relpath = $base.MakeRelativeUri($fullpath).ToString() -replace '/', '\'
            $qemu_cmd = ("pushd ${relpath} && wsl qemu-system-x86_64 -m 4096" +
              " -drive if=pflash,format=raw,readonly=on,file=FV/OVMF_CODE.fd" +
              " -drive if=pflash,format=raw,file=FV/OVMF_VARS.fd" +
              " -drive file=efi_disk.vhdx,format=vhdx")
            Out-File -FilePath "${env:ARTIFACT_PATH}\wsl_emu.bat" -InputObject $qemu_cmd -Encoding ascii
            Write-Output "VHD created at $VhdPath"
          } else {
              Write-Output "${OVM_OUT} does not exist"
          }

      - name: Make VHDX File in pwsh for win2022
        shell: pwsh
        if: ${{ github.event.inputs.vs_year == '22' }}
        run: |
          $OVM_OUT = "${env:ARTIFACT_PATH}\Ovmf${env:ARCH}\${env:TRGT}_${env:CHAIN}"
          if (Test-Path -path $OVM_OUT) {
            $EMU_OUT = "${env:ARTIFACT_PATH}\Emulator${env:ARCH}\${env:TRGT}_${env:CHAIN}\${env:ARCH}\Host"
            $VhdPath = "${OVM_OUT}\efi_disk.vhdx"
            $DirectorySizeBytes = (Get-ChildItem -Path "${EMU_OUT}\EFI" -Recurse | Measure-Object -Property Length -Sum).Sum
            $VhdSizeBytes = [math]::Ceiling($DirectorySizeBytes * 2 / 1048576 ) * 1048576
            $VhdSizeBytes = [math]::Max($VhdSizeBytes, 50 * 1048576)
            if (Test-Path -path $vhdPath) {
                Remove-Item -Path $vhdPath -Force
            }
            try {
                $vhd_obj = New-VHD -Path $VhdPath -Dynamic -SizeBytes $VhdSizeBytes | Mount-VHD -Passthru
                $dsk_cim = $vhd_obj | Initialize-Disk -PartitionStyle MBR -Passthru
                $prt_cim = $dsk_cim | New-Partition -AssignDriveLetter -UseMaximumSize
                $prt_cim | Format-Volume -FileSystem FAT -Force
                $VhdDriveLetter = $prt_cim.DriveLetter
                Copy-Item -Path ${EMU_OUT}\EFI -Destination "${VhdDriveLetter}:\" -Recurse -Force
            } finally {
                Remove-PartitionAccessPath -DiskNumber $prt_cim.DiskNumber -PartitionNumber $prt_cim.PartitionNumber -AccessPath "${VhdDriveLetter}:"
                Dismount-VHD -Path $VhdPath
            }
            $base = New-Object System.Uri("${env:ARTIFACT_PATH}\")
            $fullpath = New-Object System.Uri("${OVM_OUT}")
            $relpath = $base.MakeRelativeUri($fullpath).ToString() -replace '/', '\'
            $qemu_cmd = ("pushd ${relpath} && wsl qemu-system-x86_64 -m 4096" +
              " -drive if=pflash,format=raw,readonly=on,file=FV/OVMF_CODE.fd" +
              " -drive if=pflash,format=raw,file=FV/OVMF_VARS.fd" +
              " -drive file=efi_disk.vhdx,format=vhdx")
            Out-File -FilePath "${env:ARTIFACT_PATH}\wsl_emu.bat" -InputObject $qemu_cmd -Encoding ascii
            Write-Output "VHD created at $VhdPath"
          } else {
              Write-Output "${OVM_OUT} does not exist"
          }

      # filename: .github/workflows/bld_cmd_ci_vs22.yml
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: >-
            ci-cmd-${{ github.event.inputs.build
            }}-vs${{ github.event.inputs.vs_year
            }}-${{ github.event.inputs.architecture
            }}-${{ github.event.inputs.target
            }}-Py_${{ github.event.inputs.python_version
            }}-h_${{ github.event.inputs.hack }}

          path: ${{ env.ARTIFACT_PATH }}\**\*

