# filename: .github/workflows/bld_cmd_ci.yml
name: Debug CI
run-name: debug${{ github.event.inputs.vs_year }}-${{ github.event.inputs.architecture }}-${{ github.event.inputs.target }}-Py_${{ github.event.inputs.python_version }}-Hack_${{ github.event.inputs.hack }}

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually
    inputs:
      hack:
        description: "Enable HACK mode"
        required: false
        default: "false"
      full:
        description: "Build the most targets"
        required: false
        default: "false"
      vs_year:
        description: "Visual Studio Year ( 22 | 19 | 15 )"
        required: false
        default: "22"
      target:
        description: "Build target (DEBUG | RELEASE)"
        required: false
        default: "DEBUG"
      architecture:
        description: "Build architecture (X64 | IA32 | AARM64)"
        required: false
        default: "X64"
      python_version:
        description: "Python version to use"
        required: false
        default: "3.12.9"

jobs:
  build:
    # Use the Windows Server 2022 runner
    runs-on: windows-20${{ github.event.inputs.vs_year }}
    # https://docs.github.com/en/actions/writing-workflows
    #  /choosing-what-your-workflow-does
    #  /accessing-contextual-information-about-workflow-runs
    env:
      GH_WORKSPACE: ${{ github.workspace }}
      GH_HEAD_SHA: ${{ github.sha }}
      IASL_PREFIX: C:\ProgramData\chocolatey\bin\
      CLANG_BIN: C:\Program Files\LLVM\bin\
      NASM_PREFIX: C:\Program Files\NASM\
      PYTHON_COMMAND: python.exe
      PYTHON_PATH: D:\Python${{ github.event.inputs.python_version }}
      PYTHON_VERSION: ${{ github.event.inputs.python_version }}
      PYTHON_SETUP: python-${{ github.event.inputs.python_version }}-amd64.exe
      STUART: D:\Python${{ github.event.inputs.python_version }}\Scripts\stuart
      GH_REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      GH_WORKFLOW_NAME: ${{ github.workflow }}
      BUILD_BAT: mk_bat.py
      REPO_PATH: D:\r
      EDK2_PATH: D:\r\Edk2
      ARTIFACT_PATH: D:\artifact
      EMU_HOST: WinHost
      CHAIN: VS20${{ github.event.inputs.vs_year }}
      ARCH: ${{ github.event.inputs.architecture }}
      TRGT: ${{ github.event.inputs.target }}

    defaults:
      run:
        shell: cmd
    steps:
      - name: List Environment Variables
        run: set

      - name: Clone Repo
        run: git clone --depth 1 %GH_REPO_URL% %REPO_PATH%

      # - name: Checkout Repository recursively with long-files
      #   uses: actions/checkout@v4
      #   with:
      #     submodules: recursive     # Initialize and update submodules
      #     long-paths: true          # Enable long path support

      # - name: Install Python 3.12.9, NASM, IASL
      #   run: |
      #     curl -o ${{ github.workspace }}\%PYTHON_SETUP% https://www.python.org/ftp/python/%PYTHON_VERSION%/%PYTHON_SETUP%
      #     ${{ github.workspace }}\%PYTHON_SETUP% /quiet TargetDir=%PYTHON_PATH%

      - name: Install Pip Requirements
        run: |
          %PYTHON_COMMAND% -m pip install --upgrade pip
          %PYTHON_COMMAND% -m pip install PyYAML

      - name: Extract artifact
        run: |
          curl -Lo out.zip https://github.com/dan-bryant/test_workflow/releases/download/run_14291373102/artifact.zip
          python -m zipfile -e out.zip %ARTIFACT_PATH%
          set VOLUME=%ARTIFACT_PATH%\Emulator%ARCH%\%TRGT%_%CHAIN%\%ARCH%\%EMU_HOST%
          pushd %ARTIFACT_PATH%
          echo %cd%
          dir %cd%        

      - name: Build UEFI Volume
        continue-on-error: true        
        run: |
          set VOLUME=%ARTIFACT_PATH%\Emulator%ARCH%\%TRGT%_%CHAIN%\%ARCH%\%EMU_HOST%
          pushd %ARTIFACT_PATH%
          echo %GH_HEAD_SHA% > vmInfo%CHAIN%-%ARCH%-%TRGT%-Py%PYTHON_VERSION%.txt
          dir /s /b /a:-d > repoFileListing.txt
          dir /s /b /a:d > repoDirListing.txt
          findstr /m /c:"%GH_WORKFLOW_NAME%" %REPO_PATH%\.github\workflows\*.yml > repoWorkflowFile.txt
          for /f "delims=;" %%p in (repoWorkflowFile.txt) do (
            set GH_WORKFLOW_FILE=%%~pnxp
          )
          for %%p in (%VOLUME%) do (
            echo efiVolume: %%~pnxp>> README.txt
          )
          set BAT_FILE=build%CHAIN%-%ARCH%-%TRGT%-Py%PYTHON_VERSION%.bat
          echo pwd: %CD%
          echo PyCmd: %PYTHON_COMMAND%
          echo bld_bat.py: %REPO_PATH%\%BUILD_BAT%
          echo gh_yml: %GH_WORKFLOW_FILE%
          dir %PYTHON_COMMAND%
          dir %REPO_PATH%\%BUILD_BAT%
          type %REPO_PATH%\%BUILD_BAT%
          dir %GH_WORKFLOW_FILE%          
          type %GH_WORKFLOW_FILE%
          %PYTHON_COMMAND% %REPO_PATH%\%BUILD_BAT% D:%GH_WORKFLOW_FILE% D:%BAT_FILE%
          echo gitTag: %GH_HEAD_SHA%>> README.txt
          echo workflowFile: %GH_WORKFLOW_FILE%>> README.txt
          echo batFile: %BAT_FILE%>> README.txt
          mkdir %VOLUME%\EFI\Boot
          mkdir %VOLUME%\EFI\Tools
          for /d %%p in (*) do (
            robocopy "%ARTIFACT_PATH%\%%p\%TRGT%_%CHAIN%\%ARCH%" "%VOLUME%\EFI\Tools" *.efi /XO
          )
          copy %VOLUME%\EFI\Tools\Shell.efi %VOLUME%\EFI\Boot\bootx64.efi
          move %VOLUME%\..\%EMU_HOST%* %VOLUME%

      # filename: .github/workflows/bld_cmd_ci_vs22.yml
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug${{ github.event.inputs.vs_year }}-${{ github.event.inputs.architecture }}-${{ github.event.inputs.target }}-Py_${{ github.event.inputs.python_version }}-Hack_${{ github.event.inputs.hack }}
          path: ${{ env.ARTIFACT_PATH }}\**\*

