# filename: .github/workflows/bld_cmd_ci.yml
name: Build with CMD and CI on VS
run-name: bld-cmd-ci-vs${{ github.event.inputs.vs_year }}-${{ github.event.inputs.architecture }}-${{ github.event.inputs.target }}-Py_${{ github.event.inputs.python_version }}-Hack_${{ github.event.inputs.hack }}

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually
    inputs:
      hack:
        description: "Enable HACK mode"
        required: false
        default: "false"
      build:
        description: "Pkg ( EmulatorPkg | OvmfPkg | Edk2 | All )"
        required: false
        default: "EmulatorPkg"
      vs_year:
        description: "Visual Studio Year ( 22 | 19 )"
        required: false
        default: "22"
      target:
        description: "Build target (DEBUG | RELEASE)"
        required: false
        default: "DEBUG"
      architecture:
        description: "Build architecture (X64 | IA32 | AARM64)"
        required: false
        default: "X64"
      python_version:
        description: "Python version to use"
        required: false
        default: "3.12.9"

jobs:
  build:
    # Use the Windows Server 2022 runner
    runs-on: windows-20${{ github.event.inputs.vs_year }}
    # https://docs.github.com/en/actions/writing-workflows
    #  /choosing-what-your-workflow-does
    #  /accessing-contextual-information-about-workflow-runs
    env:
      GH_WORKSPACE: ${{ github.workspace }}
      GH_HEAD_SHA: ${{ github.sha }}
      IASL_PREFIX: C:\ProgramData\chocolatey\bin\
      CLANG_BIN: C:\Program Files\LLVM\bin\
      NASM_PREFIX: C:\Program Files\NASM\
      PYTHON_COMMAND: D:\Python${{ github.event.inputs.python_version }}\python.exe
      PYTHON_PATH: D:\Python${{ github.event.inputs.python_version }}
      PYTHON_VERSION: ${{ github.event.inputs.python_version }}
      PYTHON_SETUP: python-${{ github.event.inputs.python_version }}-amd64.exe
      STUART: D:\Python${{ github.event.inputs.python_version }}\Scripts\stuart
      GH_REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      GH_WORKFLOW_NAME: ${{ github.workflow }}
      BUILD_BAT: mk_bat.py
      REPO_PATH: D:\r
      EDK2_PATH: D:\r\Edk2
      ARTIFACT_PATH: D:\artifact
      EMU_HOST: WinHost
      CHAIN: VS20${{ github.event.inputs.vs_year }}
      ARCH: ${{ github.event.inputs.architecture }}
      TRGT: ${{ github.event.inputs.target }}

    defaults:
      run:
        shell: cmd
    steps:
      - name: Build UEFI Volume
        run: |
          set VOLUME=%ARTIFACT_PATH%\Emulator%ARCH%\%TRGT%_%CHAIN%\%ARCH%\%EMU_HOST%
          pushd %ARTIFACT_PATH%
          echo if exist %VOLUME%\..\%EMU_HOST%* ( move %VOLUME%\..\%EMU_HOST%* %VOLUME% )


