name: Manual Hello World

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  hello-world:
    runs-on: windows-2022 # Use the Windows Server 2022 runner
    defaults:
      run:
        shell: cmd

    steps:
      - name: Find Tools
        run: for /f "tokens=2 delims==:" %P in ('wmic logicaldisk get name /format:list') do (pushd %P:\ && dir /s/b nasm.exe clang.exe *asl.exe)
      
