name: Manual Hello World

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  hello-world:
    runs-on: windows-2022 # Use the Windows Server 2022 runner
    defaults:
      run:
        shell: cmd

    steps:
      - name: Find Tools
        continue-on-error: true
        run: wmic logicaldisk get name /format:list

      - name: Dir A
        continue-on-error: true
        run: pushd A:\ & dir

      - name: Dir C
        continue-on-error: true
        run: pushd C:\ & dir /s/b nasm.exe clang.exe *asl.exe       

      - name: Dir D
        continue-on-error: true
        run: pushd D:\ & dir
        
      
