name: Manual Hello World

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  hello-world:
    runs-on: windows-2022 # Use the Windows Server 2022 runner
    defaults:
      run:
        shell: cmd

    steps:
      - name: Find Tools
        continue-on-error: true
        run: for %D in (C D E F G H I J K L M N O P Q R S T U V W X Y Z) do (if exist %D:\ (pushd %D:\ && dir /s/b nasm.exe clang.exe *asl.exe))
      
