name: Manual Hello World

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  hello-world:
    runs-on: windows-2022 # Use the Windows Server 2022 runner
    defaults:
      run:
        shell: cmd

    steps:
      - name: Find Tools
        continue-on-error: true
        run: wmic logicaldisk get name /format:list
      
