name: VS2022 X64 CMD CI Build

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  hello-world:
    runs-on: windows-2022 # Use the Windows Server 2022 runner
    defaults:
      run:
        shell: cmd        
    steps:
      - name: Install LLVM
        env:
        run: winget install --source winget --id LLVM.LLVM

      - name: Install NASM
        env:
        run: winget install --source winget --id NASM.NASM

      - name: Install IASL
        run: choco install iasl

      - name: Find Binaries
        env:
          IASL_PREFIX: C:\ProgramData\chocolatey\bin\
          CLANG_BIN: C:\Program Files\LLVM\bin\
          NASM_PREFIX: C:\Program Files\NASM\
          CHAIN: VS2022
          ARCH: X64
          TRGT: DEBUG
        continue-on-error: true
        run: dir /s/b %IASL_PREFIX%\*.exe %CLANG_BIN%\*.exe %NASM_PREFIX%\*.exe 

              
